version: '3'

services:
  api:
    image: oai-proxy:latest
    container_name: oai-proxy
    environment:
      - LOGFIRE_TOKEN=pylf_v1_us_ZCPt1SQLNS753msYxLNBMXDlvQlKDc85SPfJYSj42D3N
    network_mode: "host"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
